#!/bin/bash

if [ $BUILDKITE_SOURCE != "ui" ]; then
    exit 0
fi

# Check if the environment variable BUILDKITE_BRANCH is set
# This should always be the case, but we should handle situations where it isn't
if [ -z "$BUILDKITE_BRANCH" ]; then
    echo "ERROR: BUILDKITE_BRANCH environment variable is not set."
    exit 1
fi

# Get the current commit SHA
current_commit=$(git rev-parse $BUILDKITE_COMMIT)

# Get the branch name of the commit SHA
commit_branch=$(git name-rev --name-only $current_commit)

# Check if the current branch name matches BUILDKITE_BRANCH
if [ "$commit_branch" != "$BUILDKITE_BRANCH" ]; then
    if [ "$BUILDKITE_PLUGIN_BRANCH_COMMIT_MODE" == "strict" ]; then
        echo "ERROR: Commit branch ($commit_branch) does not match BUILDKITE_BRANCH ($BUILDKITE_BRANCH)."
        exit 1
    elif [ "$BUILDKITE_PLUGIN_BRANCH_COMMIT_MODE" == "warn" ]; then
        echo -e "\033[0;33mWARNING: Commit branch ($commit_branch) does not match BUILDKITE_BRANCH ($BUILDKITE_BRANCH).\033[0m"
    fi
fi
